//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDIS.DataAccess.NavServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceManagement", ConfigurationName="NavServiceReference.SalesInvoiceManagement_Port")]
    public interface SalesInvoiceManagement_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (SalesHeader_Result) of message SalesHeader_Result does not match the default value (SalesHeader)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceManagement:SalesHeader", ReplyAction="*")]
        PDIS.DataAccess.NavServiceReference.SalesHeader_Result SalesHeader(PDIS.DataAccess.NavServiceReference.SalesHeader request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceManagement:SalesHeader", ReplyAction="*")]
        System.Threading.Tasks.Task<PDIS.DataAccess.NavServiceReference.SalesHeader_Result> SalesHeaderAsync(PDIS.DataAccess.NavServiceReference.SalesHeader request);
        
        // CODEGEN: Generating message contract since the wrapper name (SalesLine_Result) of message SalesLine_Result does not match the default value (SalesLine)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceManagement:SalesLine", ReplyAction="*")]
        PDIS.DataAccess.NavServiceReference.SalesLine_Result SalesLine(PDIS.DataAccess.NavServiceReference.SalesLine request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceManagement:SalesLine", ReplyAction="*")]
        System.Threading.Tasks.Task<PDIS.DataAccess.NavServiceReference.SalesLine_Result> SalesLineAsync(PDIS.DataAccess.NavServiceReference.SalesLine request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SalesHeader", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceManagement", IsWrapped=true)]
    public partial class SalesHeader {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceManagement", Order=0)]
        public string docNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceManagement", Order=1)]
        public string custNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceManagement", Order=2)]
        public string postDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceManagement", Order=3)]
        public string type;
        
        public SalesHeader() {
        }
        
        public SalesHeader(string docNo, string custNo, string postDate, string type) {
            this.docNo = docNo;
            this.custNo = custNo;
            this.postDate = postDate;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SalesHeader_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceManagement", IsWrapped=true)]
    public partial class SalesHeader_Result {
        
        public SalesHeader_Result() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SalesLine", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceManagement", IsWrapped=true)]
    public partial class SalesLine {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceManagement", Order=0)]
        public string no;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceManagement", Order=1)]
        public decimal qty;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceManagement", Order=2)]
        public decimal unitPrice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceManagement", Order=3)]
        public string docNo;
        
        public SalesLine() {
        }
        
        public SalesLine(string no, decimal qty, decimal unitPrice, string docNo) {
            this.no = no;
            this.qty = qty;
            this.unitPrice = unitPrice;
            this.docNo = docNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SalesLine_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/SalesInvoiceManagement", IsWrapped=true)]
    public partial class SalesLine_Result {
        
        public SalesLine_Result() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SalesInvoiceManagement_PortChannel : PDIS.DataAccess.NavServiceReference.SalesInvoiceManagement_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalesInvoiceManagement_PortClient : System.ServiceModel.ClientBase<PDIS.DataAccess.NavServiceReference.SalesInvoiceManagement_Port>, PDIS.DataAccess.NavServiceReference.SalesInvoiceManagement_Port {
        
        public SalesInvoiceManagement_PortClient() {
        }
        
        public SalesInvoiceManagement_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalesInvoiceManagement_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesInvoiceManagement_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesInvoiceManagement_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PDIS.DataAccess.NavServiceReference.SalesHeader_Result PDIS.DataAccess.NavServiceReference.SalesInvoiceManagement_Port.SalesHeader(PDIS.DataAccess.NavServiceReference.SalesHeader request) {
            return base.Channel.SalesHeader(request);
        }
        
        public void SalesHeader(string docNo, string custNo, string postDate, string type) {
            PDIS.DataAccess.NavServiceReference.SalesHeader inValue = new PDIS.DataAccess.NavServiceReference.SalesHeader();
            inValue.docNo = docNo;
            inValue.custNo = custNo;
            inValue.postDate = postDate;
            inValue.type = type;
            PDIS.DataAccess.NavServiceReference.SalesHeader_Result retVal = ((PDIS.DataAccess.NavServiceReference.SalesInvoiceManagement_Port)(this)).SalesHeader(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PDIS.DataAccess.NavServiceReference.SalesHeader_Result> PDIS.DataAccess.NavServiceReference.SalesInvoiceManagement_Port.SalesHeaderAsync(PDIS.DataAccess.NavServiceReference.SalesHeader request) {
            return base.Channel.SalesHeaderAsync(request);
        }
        
        public System.Threading.Tasks.Task<PDIS.DataAccess.NavServiceReference.SalesHeader_Result> SalesHeaderAsync(string docNo, string custNo, string postDate, string type) {
            PDIS.DataAccess.NavServiceReference.SalesHeader inValue = new PDIS.DataAccess.NavServiceReference.SalesHeader();
            inValue.docNo = docNo;
            inValue.custNo = custNo;
            inValue.postDate = postDate;
            inValue.type = type;
            return ((PDIS.DataAccess.NavServiceReference.SalesInvoiceManagement_Port)(this)).SalesHeaderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PDIS.DataAccess.NavServiceReference.SalesLine_Result PDIS.DataAccess.NavServiceReference.SalesInvoiceManagement_Port.SalesLine(PDIS.DataAccess.NavServiceReference.SalesLine request) {
            return base.Channel.SalesLine(request);
        }
        
        public void SalesLine(string no, decimal qty, decimal unitPrice, string docNo) {
            PDIS.DataAccess.NavServiceReference.SalesLine inValue = new PDIS.DataAccess.NavServiceReference.SalesLine();
            inValue.no = no;
            inValue.qty = qty;
            inValue.unitPrice = unitPrice;
            inValue.docNo = docNo;
            PDIS.DataAccess.NavServiceReference.SalesLine_Result retVal = ((PDIS.DataAccess.NavServiceReference.SalesInvoiceManagement_Port)(this)).SalesLine(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PDIS.DataAccess.NavServiceReference.SalesLine_Result> PDIS.DataAccess.NavServiceReference.SalesInvoiceManagement_Port.SalesLineAsync(PDIS.DataAccess.NavServiceReference.SalesLine request) {
            return base.Channel.SalesLineAsync(request);
        }
        
        public System.Threading.Tasks.Task<PDIS.DataAccess.NavServiceReference.SalesLine_Result> SalesLineAsync(string no, decimal qty, decimal unitPrice, string docNo) {
            PDIS.DataAccess.NavServiceReference.SalesLine inValue = new PDIS.DataAccess.NavServiceReference.SalesLine();
            inValue.no = no;
            inValue.qty = qty;
            inValue.unitPrice = unitPrice;
            inValue.docNo = docNo;
            return ((PDIS.DataAccess.NavServiceReference.SalesInvoiceManagement_Port)(this)).SalesLineAsync(inValue);
        }
    }
}
