//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDIS.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PDIS : DbContext
    {
        public PDIS()
            : base("name=PDIS")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Price> Price { get; set; }
        public virtual DbSet<Quote> Quote { get; set; }
        public virtual DbSet<CargoType> CargoType { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<RouteData> RouteData { get; set; }
    }
}
