//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDIS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public string Id { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public decimal WeightFrom { get; set; }
        public decimal WeightTo { get; set; }
        public decimal Price1 { get; set; }
    }
}
