//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDIS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public string Id { get; set; }
        public string Supplier_Id { get; set; }
        public decimal QuotedPrice { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string Type_Id { get; set; }
        public decimal Weight { get; set; }
        public decimal Widest_Dimension { get; set; }
        public decimal TransportTime { get; set; }
        public System.DateTime ValidUntil { get; set; }
        public bool Accepted { get; set; }
    }
}
